# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\omniglue\omniglue\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(891, 625)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(243,243,243);\n"
"border-color:rgb(144,167,164);")
        self.gridLayout_11 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.sideBar = QtWidgets.QWidget(Dialog)
        self.sideBar.setStyleSheet("QWidget{\n"
"    background-color: rgb(251,251,251);\n"
"    border-radius:10px;\n"
"    border-bottom:2px solid rgb(232,232,232);\n"
"    border-left:3px solid rgb(232,232,232);\n"
"}")
        self.sideBar.setObjectName("sideBar")
        self.gridLayout = QtWidgets.QGridLayout(self.sideBar)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Order1_bar = QtWidgets.QToolButton(self.sideBar)
        self.Order1_bar.setStyleSheet("/* 默认 */\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    background-color: rgb(251,251,251);\n"
"    color: rgb(44,44,44);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(246,246,246);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color: rgb(234,234,234);\n"
"    color:rgb(44,44,44);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/查询马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Order1_bar.setIcon(icon1)
        self.Order1_bar.setIconSize(QtCore.QSize(40, 40))
        self.Order1_bar.setCheckable(True)
        self.Order1_bar.setAutoExclusive(True)
        self.Order1_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Order1_bar.setObjectName("Order1_bar")
        self.verticalLayout_10.addWidget(self.Order1_bar)
        self.Order2_bar = QtWidgets.QToolButton(self.sideBar)
        self.Order2_bar.setMinimumSize(QtCore.QSize(86, 90))
        self.Order2_bar.setStyleSheet("/* 默认 */\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    background-color: rgb(251,251,251);\n"
"    color: rgb(44,44,44);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(237,237,237);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color: rgb(234,234,234);\n"
"    color:rgb(44,44,44);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/成本数据录入_编辑录入操作_jurassic马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Order2_bar.setIcon(icon2)
        self.Order2_bar.setIconSize(QtCore.QSize(40, 40))
        self.Order2_bar.setCheckable(True)
        self.Order2_bar.setAutoExclusive(True)
        self.Order2_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Order2_bar.setObjectName("Order2_bar")
        self.verticalLayout_10.addWidget(self.Order2_bar)
        self.Order3_bar = QtWidgets.QToolButton(self.sideBar)
        self.Order3_bar.setMinimumSize(QtCore.QSize(86, 90))
        self.Order3_bar.setStyleSheet("/* 默认 */\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    background-color: rgb(251,251,251);\n"
"    color: rgb(44,44,44);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(246,246,246);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color: rgb(234,234,234);\n"
"    color:rgb(44,44,44);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/图片比对马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Order3_bar.setIcon(icon3)
        self.Order3_bar.setIconSize(QtCore.QSize(40, 40))
        self.Order3_bar.setCheckable(True)
        self.Order3_bar.setAutoExclusive(True)
        self.Order3_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Order3_bar.setObjectName("Order3_bar")
        self.verticalLayout_10.addWidget(self.Order3_bar)
        self.Order4_bar = QtWidgets.QToolButton(self.sideBar)
        self.Order4_bar.setMinimumSize(QtCore.QSize(86, 90))
        self.Order4_bar.setStyleSheet("/* 默认 */\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    background-color: rgb(251,251,251);\n"
"    color: rgb(44,44,44);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(246,246,246);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color: rgb(234,234,234);\n"
"    color:rgb(44,44,44);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/关于马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Order4_bar.setIcon(icon4)
        self.Order4_bar.setIconSize(QtCore.QSize(40, 40))
        self.Order4_bar.setCheckable(True)
        self.Order4_bar.setAutoExclusive(True)
        self.Order4_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Order4_bar.setObjectName("Order4_bar")
        self.verticalLayout_10.addWidget(self.Order4_bar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.sideBar, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.order1_2 = QtWidgets.QWidget()
        self.order1_2.setObjectName("order1_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.order1_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.order1_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(41,41,41);")
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.frame_4 = QtWidgets.QFrame(self.order1_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/原图马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.line_7 = QtWidgets.QFrame(self.frame_4)
        self.line_7.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 70))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/图片编辑马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.line_8 = QtWidgets.QFrame(self.frame_4)
        self.line_8.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/照相机-马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon7)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoExclusive(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_3.setMinimumSize(QtCore.QSize(500, 300))
        self.graphicsView_3.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_5.addWidget(self.graphicsView_3)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/运行-马尔斯绿.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon8)
        self.pushButton_10.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_5.addWidget(self.pushButton_10)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.order1_2)
        self.order2_2 = QtWidgets.QWidget()
        self.order2_2.setObjectName("order2_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.order2_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.order2_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(41,41,41);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.frame_6 = QtWidgets.QFrame(self.order2_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setAutoExclusive(False)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.line_4 = QtWidgets.QFrame(self.frame_6)
        self.line_4.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 70))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setAutoExclusive(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.line_5 = QtWidgets.QFrame(self.frame_6)
        self.line_5.setStyleSheet("background-color: rgb(232,232,232);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setAutoExclusive(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.line_6 = QtWidgets.QFrame(self.frame_6)
        self.line_6.setStyleSheet("background-color: rgb(232,232,232);")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.frame_6)
        self.graphicsView_5.setMinimumSize(QtCore.QSize(500, 300))
        self.graphicsView_5.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_6.addWidget(self.graphicsView_5)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_6.addWidget(self.pushButton_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.order2_2)
        self.order3_2 = QtWidgets.QWidget()
        self.order3_2.setObjectName("order3_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.order3_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3 = QtWidgets.QLabel(self.order3_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(41,41,41);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.order3_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView.setStyleSheet("background-color: rgb(251,251,251);\n"
"border-radius:10px;\n"
"border:1.5px solid rgb(232,232,232)")
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.graphicsView)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.order3_2)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.line.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.order3_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 70))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame_2)
        self.graphicsView_2.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsView_2.setStyleSheet("background-color: rgb(251,251,251);\n"
"border-radius:10px;\n"
"border:1.5px solid rgb(232,232,232)")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout_4.addWidget(self.graphicsView_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.line_2 = QtWidgets.QFrame(self.order3_2)
        self.line_2.setStyleSheet("background-color: rgb(232,232,232);\n"
"border-color:rgb(232,232,232)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.frame_3 = QtWidgets.QFrame(self.order3_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setStyleSheet("color: rgb(41,41,41);\n"
"font: 14pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setStyleSheet("color:rgb(41,41,41);\n"
"font: 11pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_5.addWidget(self.horizontalSlider)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.order3_2)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.gridLayout_9.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.order3_2)
        self.order4_2 = QtWidgets.QWidget()
        self.order4_2.setObjectName("order4_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.order4_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.order4_2)
        self.label_4.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(41,41,41);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.order4_2)
        self.textEdit.setStyleSheet("background-color:rgb(251,251,251);\n"
"border-radius:10px;\n"
"color:rgb(58,104,76);\n"
"border:1.5px solid rgb(231,231,231);\n"
"font: 12pt \"微软雅黑\";")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.order4_2)
        self.gridLayout_11.addWidget(self.stackedWidget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "慧眼鉴真"))
        self.Order1_bar.setText(_translate("Dialog", "鉴别"))
        self.Order2_bar.setText(_translate("Dialog", "录入数据"))
        self.Order3_bar.setText(_translate("Dialog", "基本演示"))
        self.Order4_bar.setText(_translate("Dialog", "关于"))
        self.label.setText(_translate("Dialog", "鉴别"))
        self.pushButton_4.setText(_translate("Dialog", "选择原图片"))
        self.pushButton_5.setText(_translate("Dialog", "选择预处理过的图片"))
        self.pushButton_6.setText(_translate("Dialog", "拍照并预处理"))
        self.pushButton_10.setText(_translate("Dialog", "开始检测"))
        self.label_2.setText(_translate("Dialog", "录入数据"))
        self.pushButton_7.setText(_translate("Dialog", "录入预处理图片"))
        self.pushButton_8.setText(_translate("Dialog", "拍照并处理图片"))
        self.pushButton_9.setText(_translate("Dialog", "录入原图片"))
        self.pushButton_11.setText(_translate("Dialog", "开始录入"))
        self.label_3.setText(_translate("Dialog", "基本演示"))
        self.pushButton.setText(_translate("Dialog", "选择图片 1"))
        self.pushButton_2.setText(_translate("Dialog", "选择图片 2"))
        self.label_5.setText(_translate("Dialog", "选择置信度"))
        self.label_8.setText(_translate("Dialog", "0"))
        self.pushButton_3.setText(_translate("Dialog", "开始匹配"))
        self.label_4.setText(_translate("Dialog", "关于"))
# import resources_rc
