# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\omniglue\omniglue\Output_cmd_graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:rgb(243,243,243);\n"
"border-color:rgb(144,167,164);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmdButton = QtWidgets.QPushButton(Dialog)
        self.cmdButton.setMinimumSize(QtCore.QSize(500, 25))
        self.cmdButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cmdButton.setStyleSheet("font: 11pt \"微软雅黑\";\n"
"background-color:rgb(251,251,251);\n"
"color:rgb(41,41,41);\n"
"border-radius:10px;\n"
"border-bottom:1.5px solid rgb(231,231,231)")
        self.cmdButton.setObjectName("cmdButton")
        self.verticalLayout.addWidget(self.cmdButton)
        self.CmdShow = QtWidgets.QTextEdit(Dialog)
        self.CmdShow.setMinimumSize(QtCore.QSize(0, 300))
        self.CmdShow.setStyleSheet("background-color:rgb(251,251,251);\n"
"border-radius:10px;\n"
"color:rgb(58,104,76);\n"
"border:1.5px solid rgb(231,231,231);")
        self.CmdShow.setReadOnly(True)
        self.CmdShow.setObjectName("CmdShow")
        self.verticalLayout.addWidget(self.CmdShow)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "慧眼鉴真(运行提示)"))
        self.cmdButton.setText(_translate("Dialog", "运行提示"))
