# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\omniglue\omniglue\takephotoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_takephoto(object):
    def setupUi(self, takephoto):
        takephoto.setObjectName("takephoto")
        takephoto.resize(996, 476)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("g:\\omniglue\\omniglue\\icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        takephoto.setWindowIcon(icon)
        takephoto.setStyleSheet("background-color: rgb(243,243,243);\n"
"border-color:rgb(144,167,164);")
        self.gridLayout_5 = QtWidgets.QGridLayout(takephoto)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(takephoto)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(400, 0))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(takephoto)
        self.label.setMinimumSize(QtCore.QSize(509, 389))
        self.label.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(251,251,251);\n"
"border-bottom:1.5px solid rgb(231,231,231);\n"
"border:1.5px solid rgb(231,231,231)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(takephoto)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(281, 0))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(44,44,44);\n"
"    background-color: rgb(251,251,251);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    font: 11pt \"微软雅黑\";\n"
"    border:1.5px solid rgb(232,232,232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(237,237,237)\n"
"}\n"
"QPushButton:pressed,QPushButton:checked\n"
"{\n"
"    border-left: 3px outset rgb(58,104,76);\n"
"    background-color:rgb(234,234,234)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.photo1 = QtWidgets.QGraphicsView(self.frame)
        self.photo1.setMinimumSize(QtCore.QSize(141, 91))
        self.photo1.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo1.setObjectName("photo1")
        self.gridLayout.addWidget(self.photo1, 0, 0, 1, 1)
        self.photo2 = QtWidgets.QGraphicsView(self.frame)
        self.photo2.setMinimumSize(QtCore.QSize(141, 91))
        self.photo2.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo2.setObjectName("photo2")
        self.gridLayout.addWidget(self.photo2, 0, 1, 1, 1)
        self.photo3 = QtWidgets.QGraphicsView(self.frame)
        self.photo3.setMinimumSize(QtCore.QSize(141, 91))
        self.photo3.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo3.setObjectName("photo3")
        self.gridLayout.addWidget(self.photo3, 0, 2, 1, 1)
        self.photo4 = QtWidgets.QGraphicsView(self.frame)
        self.photo4.setMinimumSize(QtCore.QSize(141, 91))
        self.photo4.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo4.setObjectName("photo4")
        self.gridLayout.addWidget(self.photo4, 1, 0, 1, 1)
        self.photo5 = QtWidgets.QGraphicsView(self.frame)
        self.photo5.setMinimumSize(QtCore.QSize(141, 91))
        self.photo5.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo5.setObjectName("photo5")
        self.gridLayout.addWidget(self.photo5, 1, 1, 1, 1)
        self.photo6 = QtWidgets.QGraphicsView(self.frame)
        self.photo6.setMinimumSize(QtCore.QSize(141, 91))
        self.photo6.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo6.setObjectName("photo6")
        self.gridLayout.addWidget(self.photo6, 1, 2, 1, 1)
        self.photo7 = QtWidgets.QGraphicsView(self.frame)
        self.photo7.setMinimumSize(QtCore.QSize(141, 91))
        self.photo7.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo7.setObjectName("photo7")
        self.gridLayout.addWidget(self.photo7, 2, 0, 1, 1)
        self.photo8 = QtWidgets.QGraphicsView(self.frame)
        self.photo8.setMinimumSize(QtCore.QSize(141, 91))
        self.photo8.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo8.setObjectName("photo8")
        self.gridLayout.addWidget(self.photo8, 2, 1, 1, 1)
        self.photo9 = QtWidgets.QGraphicsView(self.frame)
        self.photo9.setMinimumSize(QtCore.QSize(141, 91))
        self.photo9.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo9.setObjectName("photo9")
        self.gridLayout.addWidget(self.photo9, 2, 2, 1, 1)
        self.photo10 = QtWidgets.QGraphicsView(self.frame)
        self.photo10.setMinimumSize(QtCore.QSize(141, 91))
        self.photo10.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo10.setObjectName("photo10")
        self.gridLayout.addWidget(self.photo10, 3, 0, 1, 1)
        self.photo11 = QtWidgets.QGraphicsView(self.frame)
        self.photo11.setMinimumSize(QtCore.QSize(141, 91))
        self.photo11.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo11.setObjectName("photo11")
        self.gridLayout.addWidget(self.photo11, 3, 1, 1, 1)
        self.photo12 = QtWidgets.QGraphicsView(self.frame)
        self.photo12.setMinimumSize(QtCore.QSize(141, 91))
        self.photo12.setStyleSheet("QGraphicsView{\n"
"background-color: rgb(251,251,251);\n"
"border-radius: 10px;\n"
"border:1.5px solid rgb(232,232,232);\n"
"}")
        self.photo12.setObjectName("photo12")
        self.gridLayout.addWidget(self.photo12, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(takephoto)
        QtCore.QMetaObject.connectSlotsByName(takephoto)

    def retranslateUi(self, takephoto):
        _translate = QtCore.QCoreApplication.translate
        takephoto.setWindowTitle(_translate("takephoto", "慧眼鉴真(拍照界面)"))
        self.pushButton_3.setText(_translate("takephoto", "选择文件夹"))
        self.pushButton.setText(_translate("takephoto", "拍照"))
        self.label.setText(_translate("takephoto", "TextLabel"))
        self.pushButton_4.setText(_translate("takephoto", "重新拍摄"))
        self.pushButton_2.setText(_translate("takephoto", "开始预处理"))
